### ISSUE TITLE
[CS:GO] Events causing a sql error

### ISSUE THREAD

**Issue by Thomaxius** [BigBrotherBot/big-brother-bot#281] opened 2015-02-08 11:16 UTC
So, csgo has events 'throw' and 'purchased', which both cause a SQL error:

    150208 00:44:06	CONSOLE	'L 02/08/2015 - 00:44:06: "Ivan<32><BOT><CT>" threw hegrenade [-578 -846 -304]'
    150208 00:44:06	ERROR	u'Query failed [INSERT INTO xlr_actionstats (`name`, `count`) VALUES ("threw "hegrenade"", 1)] (mysql error crap here)

Now, this is easily fixed by changing cs:go parser:
`return self.getEvent("EVT_CLIENT_ACTION", client=client, data='threw "%s"' % item)`
to
`return self.getEvent("EVT_CLIENT_ACTION", client=client, data='threw %s' % item)`

But I'm wondering if this is a sqlite thing again, and one would have to find a solution that works for both protocols. Or I can just push that code and it works fine for both?

**Comment by danielepantaleone** [comment] 2015-02-08 12:26
Could you please show the portion of code where this SQL query is generated? If it's an escape problem it needs to be fixed in the storage module. Could you show the full log with the exception being logged?

**Comment by Thomaxius** [comment] 2015-02-08 13:29
150208 00:44:06	CONSOLE	'L 02/08/2015 - 00:44:06: "Ivan<32><BOT><CT>" threw hegrenade [-578 -846 -304]'
150208 00:44:06	VERBOSE	u'Queueing event Client Action : threw "hegrenade"'
150208 00:44:06	VERBOSE	'Parsing event: Client Action: XlrstatsPlugin'
150208 00:44:06	ERROR	u'Query failed [INSERT INTO xlr_actionstats (`name`, `count`) VALUES ("threw "hegrenade"", 1)] None: (1064, u\'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\'hegrenade"", 1)\\\' at line 1\')'

Here's the xlrstats query:
    def _insertquery(self):
        q = """INSERT INTO %s (`name`, `count`) VALUES ("%s", %s)""" % (self._table, self.name, self.count)
        return q

I can give the b3.log, but i don't see a reason as the log entry where the error happens is above.

**Comment by danielepantaleone** [comment] 2015-02-08 13:34
The problem is in the quoting of the SQL query. I'll provide a fix in a PR

**Comment by Thomaxius** [comment] 2015-02-08 15:44
Righto, all good then.

**Comment by thomasleveil** [comment] 2015-02-08 23:19
fix available in [B3 daily build 313](http://files.cucurb.net/b3/daily/)

**Closed by thomasleveil** 2015-02-08 23:19 UTC
Labels: bug, important
