### ISSUE TITLE
[IOURT42] Nicknames with double slashes "//" making mess with B3.

### ISSUE THREAD

**Issue by Yascor** [BigBrotherBot/big-brother-bot#341] opened 2015-06-16 15:08 UTC
Hey, is it possible to cut off double and more slashes from players nicknames?
For now some people connecting with names like "//BLABLA//" etc and bot everytime when sending rcon say/tell etc will cut all message/notifications which got "//". 

ps Sorry, I accidently clicked Enter during topic edition :P

**Comment by danielepantaleone** [comment] 2015-06-16 15:12
Could you provide a description of the problem?

**Comment by danielepantaleone** [comment] 2015-06-16 15:16
I'm not sure I entirely understood the problem. Could you provide some examples?

**Comment by Yascor** [comment] 2015-06-16 15:19
Just change nick '/name "//somename"' and connect to every b3 server with plugin welcome, you will only see first part of message. or try type !list it will cut off everything else after name with double slashes.

**Comment by danielepantaleone** [comment] 2015-06-16 15:21
Do you have a log showing this problem? I do not have any servers at the moment on which I can test this behavior, so I'm left with automated tests. Also, is this problem bounded to a single game or does it happen on different games?

**Comment by Yascor** [comment] 2015-06-16 15:34
Its log but it wont show you anything: https://gist.github.com/Yascor/66f22b6366d26f77949c#file-b3-log

> VERBOSE	"RCON sending (127.0.0.1:1234) 'tell 0 ^8[pm]^7 ^7//somename [^20^7]'"

Bot sending by rcon above message but in game you will only see this part: "^8[pm]^7 ^7" everything else after slashes wont show, that how iourt engine works since always I think and maybe other q3a based games. People cant type full links with http://blablabla.com and rcon cant to that too.

**Comment by danielepantaleone** [comment] 2015-06-16 15:36
Then the problem is not on B3 side but on UrT side. You should contact UrT developers and ask for a fix for this problem. There is nothing B3 can do I'm afraid. Removing the double slash it's not an option since it will generate inconsistent data.

**Closed** 2015-06-16 15:36 UTC

**Comment by Yascor** [comment] 2015-06-16 15:38
Ye figured out that, I hope it isnt kind of hardcoded in game. Will let them know too :)
